### ISSUE TITLE
Server Connected, But no communication between clients tabs

### ISSUE THREAD

**Issue by mukilana** [muuknl/phprealtimechat#11]
I run the server page through command prompt (>php server.php) and server start listening.
Next, open client page in two tabs of chrome browser tab. 

But no communication happened between two tabs. The message sent was only displayed in single tab.

Please give me a solution in this issue.

**Comment by muuknl** [comment]
Does the console give any errors?

**Comment by mukilana** [comment]
Thanks for reply, Console does not give any error. 
Chat system work fine, when server accessed from remote system. 
While testing through browser tabs it does not broadcast the message.

Sometimes the server console throw 10053 error. But it not happened regularly.

The screenshot of chat system working is given below
![chaterror](https://cloud.githubusercontent.com/assets/22561177/19064457/1a08e848-8a2b-11e6-849e-da49bd646045.jpg)

Please guide me on this issue. Thank you @muuknl

**Comment by muuknl** [comment]
Are you following the tutorial series, or have you copied the repository.

**Comment by mukilana** [comment]
I am download the source from your github repository. Now i m using Wamp Server.

**Comment by muuknl** [comment]
That's very odd, since this should work if you pulled directly from github repo. I am not really sure how I can help you further, but you should try to research websockets a little and then I'm sure you can figure it out.
