### ISSUE TITLE
Cant start on Debian Vps 

### ISSUE THREAD

**Issue by HyperGainZ** [muuknl/phprealtimechat#3]
when i  try to start it on my debiab vps i get this error
```
PHP Fatal error:  Class 'Ratchet\http\HttpServer' not found in /react-chat/bin/server.php on line 11
```
and during the composer install i get this warning 
![Warning](http://i.gyazo.com/7d4a4a261ba154df8c74523dd8b97446.png)

**Comment by muuknl** [comment]
Try Ratchet\Http\HttpServer (not the capital H in the Http

**Comment by HyperGainZ** [comment]
ok that works thanks or should i say Dank je :D

**Comment by muuknl** [comment]
Haha, graag gedaan :)
