### ISSUE TITLE
Broadcasting?

### ISSUE THREAD

**Issue by efrierson** [muuknl/phprealtimechat#7]
Hey - 

First, thanks for the code!  Easy to implement and get going.  I'm struggling trying to find a way to broadcast updates to all clients every 5 seconds or so.  I've put this into the Chat.php object:

```
public function broadcast()
    {
        foreach ($this->repository->getClients() as $client)
        {
            $client->sendMsg("System", "Ping!");
        }        
    }
```

How would I call this function every few seconds?  Sorry if this is a dumb question

**Comment by muuknl** [comment]
You can call `addPeriodicTimer()` on the event-loop. [This is the method on the interface](https://github.com/reactphp/event-loop/blob/master/src/LoopInterface.php#L70).
